### ISSUE TITLE
code？

### ISSUE THREAD

**Issue by zhizhuaa** [YunDuanFei/ACCNet#1]

**Comment by YunDuanFei** [comment]
Source code is opened after the manuscript is accepted. If you are a reviewer, we can provide you with some of the source code. Some of the experimental records are shown in the Appendix.


Thank you for your interest in our work and best wishes.


Sincerely,
Yunfei Liu


| |
liuyunfei_302
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/9/2023 13:51 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [YunDuanFei/ACCNet] code？ (Issue #1) |

Excuse me, where is the code？

**Comment by YunDuanFei** [comment]
Related attention modules have been updated to the Github repository.
Source code is opened after the manuscript is accepted. If you are a reviewer, we can provide you with some of the source code. Some of the experimental records are shown in the Appendix.


Thank you for your interest in our work and best wishes.


Sincerely,
Yunfei Liu




| |
liuyunfei_302
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/9/2023 13:51 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [YunDuanFei/ACCNet] code？ (Issue #1) |

Excuse me, where is the code？
